defaults:
  - task: unlearning_atu
  - hydra: default
  # Allow the model to overwrite the settings below
  - _self_
  - pre_trained_llm: phi-3.5-mini-instruct
  - experiment: ~

unlearning_target: "1_Stephen_King"

skip_initial_eval: false

seed: "257640305935986723276204284023905265734"

name: unlearning-${unlearning_target}
exp: atu-unlearning

wandb:
  id: ~
  entity: "ayushseh-carnegie-mellon-university"
  project: "idl-project-unlearning"
  group: ~
  name: atu-layer${task.training_module.pretrained_model_hook_layer}-phi3.5-mini
  mode: ~

hydra:
  job:
    name: ${exp}

trainer:
  accelerator: auto
  devices: auto
  max_epochs: -1
  log_every_n_steps: 10

early_stopping: ~

matmul_precision: medium

